# -*- coding: utf-8 -*-
"""Account-area strings that do NOT exist in rebrand/strings/*.json.

Every one of these is a DRAFT by the account-area engineer, not ratified by
the content lead or by the Russian and Armenian writers. Each is emitted into
the HTML with the marker [NEW KEY] in its comment so it can be found with one
grep. The key space is `account.*`.
"""

NEW = {
# ---- shell -----------------------------------------------------------------
"account.nav.label":        ("Account sections", "Разделы кабинета", "Անձնական էջի բաժինները"),
"account.nav.overview":     ("Overview", "Обзор", "Ընդհանուր"),
"account.nav.plots":        ("My plots", "Мои участки", "Իմ հողամասերը"),
"account.nav.packages":     ("My orders", "Мои заказы", "Իմ պատվերները"),
"account.nav.payments":     ("My payments", "Мои платежи", "Իմ վճարումները"),
"account.nav.profile":      ("My details", "Мои данные", "Իմ տվյալները"),
"account.nav.signout":      ("Sign out", "Выйти", "Ելք"),
"account.identity.label":   ("Signed in as", "Вы вошли как", "Դուք մուտք եք գործել որպես"),
"account.mainnav.label":    ("Main menu", "Основное меню", "Հիմնական ընտրացանկ"),
"account.example.legend":   ("Values in braces are filled by the server. Nothing on this page is a real customer.",
                             "Значения в фигурных скобках подставляет сервер. Ничего на этой странице не относится к реальному клиенту.",
                             "Ձևավոր փակագծերում արժեքները լրացնում է սերվերը։ Այս էջում իրական հաճախորդ չկա։"),

# ---- dashboard -------------------------------------------------------------
"account.dashboard.h1":         ("Your account", "Ваш кабинет", "Ձեր անձնական էջը"),
"account.dashboard.standfirst": ("Your plots, what you have ordered, what you have paid, and your own details. The report from each visit belongs to the plot it was made at.",
                                 "Ваши участки, заказы, платежи и Ваши данные. Отчёт о каждом визите относится к тому участку, на котором визит был.",
                                 "Ձեր հողամասերը, պատվերները, վճարումները և ձեր տվյալները։ Ամեն այցի հաշվետվությունը պատկանում է այն հողամասին, որտեղ այցը եղել է։"),
"account.dashboard.plots.title":   ("No plot on this account yet", "На этом аккаунте пока нет участка", "Այս հաշվին դեռ հողամաս չկա"),
"account.dashboard.orders.title":  ("Nothing ordered yet", "Заказов пока нет", "Դեռ պատվեր չկա"),
"account.dashboard.orders.text":   ("Care is ordered as a year of visits, as one visit, or as an inspection first.",
                                    "Уход заказывают на год, разовым визитом или начиная с осмотра.",
                                    "Խնամքը պատվիրվում է տարով, մեկանգամյա այցով կամ սկսած Զննումից։"),
"account.dashboard.reports.title": ("No reports yet", "Отчётов пока нет", "Հաշվետվություններ դեռ չկան"),
"account.dashboard.next.h2":       ("What happens next", "Что происходит дальше", "Ինչ է լինում հետո"),
"account.dashboard.step1":  ("Add the plot: the cemetery, and the sector and number if you know them.",
                             "Добавьте участок: кладбище, а также сектор и номер, если Вы их знаете.",
                             "Ավելացրեք հողամասը՝ գերեզմանոցը, իսկ եթե գիտեք՝ նաև հատվածն ու համարը։"),
"account.dashboard.step2":  ("Choose how many visits a year, or a single visit.",
                             "Выберите, сколько визитов в год — или разовый визит.",
                             "Ընտրեք՝ քանի այց տարեկան, կամ մեկ այց։"),
"account.dashboard.step3":  ("We confirm the plot with you and send the invoice.",
                             "Мы подтверждаем участок и присылаем счёт.",
                             "Մենք ձեզ հետ ճշտում ենք հողամասը և ուղարկում հաշիվը։"),
"account.dashboard.help.h2":("If something here is unclear", "Если что-то непонятно", "Եթե ինչ-որ բան պարզ չէ"),

# ---- plots -----------------------------------------------------------------
"account.plots.h1":         ("My plots", "Мои участки", "Իմ հողամասերը"),
"account.plots.standfirst": ("A plot is one grave we care for. Every visit, every report and every invoice belongs to one of them.",
                             "Участок — это одно место, за которым мы ухаживаем. Каждый визит, каждый отчёт и каждый счёт относится к одному из них.",
                             "Հողամասը մեկ վայր է, որին խնամում ենք։ Ամեն այց, ամեն հաշվետվություն և ամեն հաշիվ վերաբերում է դրանցից մեկին։"),
"account.plots.empty.title":("No plot on this account yet", "На этом аккаунте пока нет участка", "Այս հաշվին դեռ հողամաս չկա"),
"account.plots.empty.text": ("A plot is the grave we look after: the cemetery, where it stands, how large it is and how many monuments are on it. Visits, reports and invoices all hang on it.",
                             "Участок — это место, за которым мы ухаживаем: кладбище, где он находится, его площадь и число памятников. Визиты, отчёты и счета привязаны к нему.",
                             "Հողամասը այն վայրն է, որին խնամում ենք՝ գերեզմանոցը, տեղը, մակերեսը և տապանաքարերի թիվը։ Այցերը, հաշվետվություններն ու հաշիվները կապված են դրան։"),
"account.plots.add.cta":    ("Add a plot", "Добавить участок", "Ավելացնել հողամաս"),
"account.plots.table.caption": ("Plots on this account", "Участки на этом аккаунте", "Այս հաշվի հողամասերը"),
"account.plots.col.name":   ("Plot", "Участок", "Հողամաս"),
"account.plots.col.cemetery": ("Cemetery", "Кладбище", "Գերեզմանոց"),
"account.plots.col.area":   ("Area", "Площадь", "Մակերես"),
"account.plots.col.monuments": ("Monuments", "Памятники", "Տապանաքարեր"),
"account.plots.col.care":   ("Care", "Уход", "Խնամք"),
"account.plots.col.action": ("Action", "Действие", "Գործողություն"),
"account.plots.callInstead":("Would you rather tell us by phone? Call, or write on WhatsApp.",
                             "Удобнее сказать по телефону? Позвоните или напишите в WhatsApp.",
                             "Հարմա՞ր է հեռախոսով ասել։ Զանգեք կամ գրեք WhatsApp-ով։"),
"account.plots.order.cta":  ("Order care for this plot", "Заказать уход за этим участком", "Պատվիրել խնամք այս հողամասի համար"),

# ---- plot-new --------------------------------------------------------------
"account.plotnew.h1":         ("Add a plot", "Добавить участок", "Ավելացնել հողամաս"),
"account.plotnew.standfirst": ("Nothing here is checked against a registry. What you know is enough to start; the first visit records the rest.",
                               "Ничего из этого не сверяется с реестром. Достаточно того, что Вы знаете; остальное записывает первый визит.",
                               "Այստեղ ոչինչ ռեեստրի հետ չի ստուգվում։ Բավական է այն, ինչ գիտեք. մնացածը գրանցում է առաջին այցը։"),
"account.plotnew.label.name": ("What to call this plot", "Как называть этот участок", "Ինչպես անվանել այս հողամասը"),
"account.plotnew.help.name":  ("Only you and the people you invite see this name.",
                               "Это название видите Вы и те, кого Вы пригласите.",
                               "Այս անունը տեսնում եք դուք և նրանք, ում հրավիրում եք։"),
"account.plotnew.label.cemetery": ("Cemetery", "Кладбище", "Գերեզմանոց"),
"account.plotnew.help.cemetery":  ("The name of the cemetery, or the district it is in.",
                                   "Название кладбища или район, в котором оно находится.",
                                   "Գերեզմանոցի անունը կամ այն թաղամասը, որտեղ այն է։"),
"account.plotnew.label.location": ("Sector, row, number", "Сектор, ряд, номер", "Հատված, շարք, համար"),
"account.plotnew.help.location":  ("If it is written down somewhere, copy it here. If not, leave it blank — the first visit finds the plot.",
                                   "Если это где-то записано, перепишите сюда. Если нет — оставьте пустым: участок находит первый визит.",
                                   "Եթե որևէ տեղ գրված է, արտագրեք այստեղ։ Եթե ոչ՝ թողեք դատարկ. հողամասը գտնում է առաջին այցը։"),
"account.plotnew.label.area":     ("Area, m²", "Площадь, м²", "Մակերեսը, մ²"),
"account.plotnew.label.monuments":("Monuments on the plot", "Памятников на участке", "Տապանաքարերը հողամասում"),
"account.plotnew.label.showName": ("Show the name on the monument in reports", "Показывать имя с памятника в отчётах", "Ցույց տալ տապանաքարի անունը հաշվետվություններում"),
"account.plotnew.label.contact":  ("A contact in Yerevan (optional)", "Контакт в Ереване (по желанию)", "Կապ Երևանում (ըստ ցանկության)"),
"account.plotnew.label.note":     ("Anything else we should know", "Что ещё нам стоит знать", "Ուրիշ ի՞նչ պետք է իմանանք"),
"account.plotnew.help.note":      ("A gate that is locked, a neighbour who has the key, a tree that drops on the stone. Anything.",
                                   "Закрытая калитка, сосед с ключом, дерево над памятником. Что угодно.",
                                   "Փակ դարպաս, հարևան, ում մոտ բանալին է, ծառ, որ թափվում է քարին։ Ինչ ասեք։"),
"account.plotnew.fieldset":     ("The plot", "Участок", "Հողամասը"),
"account.plotnew.submit":         ("Save this plot", "Сохранить участок", "Պահպանել հողամասը"),
"account.plotnew.back":           ("Back to my plots", "К моим участкам", "Դեպի իմ հողամասերը"),
"account.optional":               ("optional", "по желанию", "ըստ ցանկության"),

# ---- order -----------------------------------------------------------------
"account.order.h1":         ("Order care", "Заказать уход", "Պատվիրել խնամք"),
"account.order.standfirst": ("Two choices: which plot, and how many visits. Nothing is charged from this page.",
                             "Два выбора: какой участок и сколько визитов. С этой страницы ничего не списывается.",
                             "Երկու ընտրություն՝ որ հողամասը և քանի այց։ Այս էջից ոչինչ չի գանձվում։"),
"account.order.step1":      ("1. Which plot", "1. Какой участок", "1. Ո՞ր հողամասը"),
"account.order.step2":      ("2. What to order", "2. Что заказать", "2. Ի՞նչ պատվիրել"),
"account.order.step3":      ("3. What this costs", "3. Сколько это стоит", "3. Որքա՞ն է դա արժե"),
"account.order.addplot":    ("Add another plot", "Добавить другой участок", "Ավելացնել այլ հողամաս"),
"account.order.noplot":     ("There is no plot on this account yet. Add one first — an order without a plot is an order without a grave.",
                             "На этом аккаунте пока нет участка. Сначала добавьте его: заказ без участка — это заказ без места.",
                             "Այս հաշվին դեռ հողամաս չկա։ Նախ ավելացրեք այն. առանց հողամասի պատվերը վայր չունի։"),
"account.order.consent":    ("I have read the service terms and the refund and cancellation terms.",
                             "Я ознакомился с условиями услуги и с условиями возврата и отмены.",
                             "Ես ծանոթացել եմ ծառայության պայմաններին և վերադարձի ու չեղարկման պայմաններին։"),
"account.order.submit":     ("Send this order", "Отправить заказ", "Ուղարկել պատվերը"),
"account.order.serverPrice":("The amount is set by us, from the service and the plot. This page cannot change it.",
                             "Сумму определяем мы — по услуге и по участку. Эта страница её не меняет.",
                             "Գումարը որոշում ենք մենք՝ ըստ ծառայության և հողամասի։ Այս էջը այն չի փոխում։"),
"account.order.summary.caption": ("How this amount is made up", "Из чего складывается сумма", "Ինչից է գոյանում գումարը"),
"account.order.next.h2":    ("What happens after you send it", "Что будет после отправки", "Ի՞նչ է լինում ուղարկելուց հետո"),

# ---- packages --------------------------------------------------------------
"account.packages.h1":         ("My orders", "Мои заказы", "Իմ պատվերները"),
"account.packages.standfirst": ("What you have ordered, what is paid, and how many visits are done.",
                                "Что заказано, что оплачено и сколько визитов выполнено.",
                                "Ինչ է պատվիրված, ինչ է վճարված և քանի այց է կատարված։"),
"account.packages.table.caption": ("Orders on this account", "Заказы на этом аккаунте", "Այս հաշվի պատվերները"),
"account.packages.col.service": ("Service", "Услуга", "Ծառայություն"),
"account.packages.col.plot":    ("Plot", "Участок", "Հողամաս"),
"account.packages.col.visits":  ("Visits done", "Выполнено визитов", "Կատարված այցեր"),
"account.packages.col.period":  ("Year", "Год", "Տարի"),
"account.packages.col.paid":    ("Paid", "Оплачено", "Վճարված"),
"account.packages.col.status":  ("Status", "Статус", "Կարգավիճակ"),
"account.packages.col.action":  ("Action", "Действие", "Գործողություն"),
"account.packages.status.active":   ("Active", "Действует", "Գործում է"),
"account.packages.status.awaiting": ("Awaiting payment", "Ожидает оплаты", "Սպասում է վճարման"),
"account.packages.status.cancelled":("Cancelled", "Отменено", "Չեղարկված"),
"account.packages.action.pay":  ("Pay", "Оплатить", "Վճարել"),
"account.packages.action.cancel":("Cancel", "Отменить", "Չեղարկել"),
"account.packages.empty.title": ("Nothing ordered yet", "Заказов пока нет", "Դեռ պատվեր չկա"),
"account.cancel.title":   ("Cancel this subscription?", "Отменить эту подписку?", "Չեղարկե՞լ այս բաժանորդագրությունը"),
"account.cancel.example": ("A worked example, with real figures:", "Пример с реальными числами:", "Օրինակ՝ իրական թվերով․"),
"account.cancel.confirm": ("Yes, cancel and refund", "Да, отменить и вернуть", "Այո՛, չեղարկել և վերադարձնել"),
"account.cancel.keep":    ("Keep the subscription", "Оставить подписку", "Թողնել բաժանորդագրությունը"),
"account.cancel.open":    ("Cancel this subscription", "Отменить эту подписку", "Չեղարկել այս բաժանորդագրությունը"),

# ---- payments --------------------------------------------------------------
"account.payments.h1":         ("My payments", "Мои платежи", "Իմ վճարումները"),
"account.payments.standfirst": ("Every charge and every invoice, in one list.",
                                "Каждое списание и каждый счёт — одним списком.",
                                "Ամեն գանձում և ամեն հաշիվ՝ մեկ ցանկում։"),
"account.payments.table.caption": ("Payments and invoices", "Платежи и счета", "Վճարումներ և հաշիվներ"),
"account.payments.col.date":   ("Date", "Дата", "Ամսաթիվ"),
"account.payments.col.what":   ("What for", "За что", "Ինչի համար"),
"account.payments.col.amount": ("Amount", "Сумма", "Գումար"),
"account.payments.col.method": ("Method", "Способ", "Եղանակ"),
"account.payments.col.status": ("Status", "Статус", "Կարգավիճակ"),
"account.payments.col.invoice":("Invoice", "Счёт", "Հաշիվ"),
"account.payments.status.paid":     ("Paid", "Оплачено", "Վճարված"),
"account.payments.status.refunded": ("Refunded", "Возвращено", "Վերադարձված"),
"account.payments.method.transfer": ("Bank transfer", "Банковский перевод", "Բանկային փոխանցում"),
"account.payments.invoice.link":    ("Download (PDF)", "Скачать (PDF)", "Ներբեռնել (PDF)"),
"account.payments.empty.title":     ("Nothing has been charged yet", "Списаний пока не было", "Դեռ ոչինչ չի գանձվել"),
"account.payments.how.h2":          ("How payment works", "Как устроена оплата", "Ինչպես է կատարվում վճարումը"),

# ---- profile ---------------------------------------------------------------
"account.profile.h1":        ("My details", "Мои данные", "Իմ տվյալները"),
"account.profile.details.h2":("Name and contacts", "Имя и контакты", "Անուն և կապ"),
"account.profile.label.fullname": ("Name and surname", "Имя и фамилия", "Անուն ազգանուն"),
"account.profile.label.phone":    ("Phone", "Телефон", "Հեռախոս"),
"account.profile.label.email":    ("E-mail", "Электронная почта", "Էլփոստ"),
"account.profile.help.email":     ("Invoices and the notice that a report is ready go to this address.",
                                   "На этот адрес приходят счета и уведомления о готовых отчётах.",
                                   "Այս հասցեին են գալիս հաշիվները և պատրաստ հաշվետվությունների ծանուցումները։"),
"account.profile.save":      ("Save", "Сохранить", "Պահպանել"),
"account.profile.password.h2":  ("Change password", "Смена пароля", "Գաղտնաբառի փոփոխություն"),
"account.profile.password.why": ("The current password is asked for here because changing a password is exactly what turns a borrowed session into a lost account.",
                                 "Текущий пароль спрашиваем потому, что именно смена пароля превращает чужую сессию в потерянный аккаунт.",
                                 "Ընթացիկ գաղտնաբառը հարցնում ենք, որովհետև հենց գաղտնաբառի փոփոխությունն է ուրիշի ձեռք ընկած մուտքը վերածում կորցրած հաշվի։"),
"account.profile.label.current":("Current password", "Текущий пароль", "Ընթացիկ գաղտնաբառը"),
"account.profile.label.new":    ("New password", "Новый пароль", "Նոր գաղտնաբառ"),
"account.profile.label.repeat": ("Repeat the new password", "Повторите новый пароль", "Կրկնեք նոր գաղտնաբառը"),
"account.profile.rules.h":      ("The new password must have:", "В новом пароле должно быть:", "Նոր գաղտնաբառը պետք է ունենա․"),
"account.profile.rule1": ("at least 8 characters", "не менее 8 символов", "առնվազն 8 նիշ"),
"account.profile.rule2": ("Latin letters, digits and the special characters listed below only",
                          "только латинские буквы, цифры и перечисленные ниже спецсимволы",
                          "միայն լատինատառեր, թվանշաններ և ներքևում թվարկված նշաններ"),
"account.profile.rule3": ("at least one small letter", "хотя бы одна строчная буква", "առնվազն մեկ փոքրատառ"),
"account.profile.rule4": ("at least one capital letter", "хотя бы одна заглавная буква", "առնվազն մեկ մեծատառ"),
"account.profile.rule5": ("at least one digit", "хотя бы одна цифра", "առնվազն մեկ թվանշան"),
"account.profile.rule6": ("at least one of @ $ ! % * ? &", "хотя бы один из @ $ ! % * ? &", "առնվազն մեկը՝ @ $ ! % * ? &"),
"account.profile.password.save": ("Change the password", "Сменить пароль", "Փոխել գաղտնաբառը"),

# ---- login / register / reset ---------------------------------------------
"account.login.h1":       ("Sign in", "Вход", "Մուտք"),
"account.login.submit":   ("Sign in", "Войти", "Մուտք գործել"),
"account.login.register": ("No account yet? Register.", "Ещё нет аккаунта? Зарегистрируйтесь.", "Դեռ հաշիվ չունե՞ք։ Գրանցվեք։"),
"account.login.reset":    ("Forgotten your password?", "Забыли пароль?", "Մոռացե՞լ եք գաղտնաբառը։"),
"account.label.password": ("Password", "Пароль", "Գաղտնաբառ"),
"account.required":       ("Fields marked * are required.", "Поля со звёздочкой обязательны.", "Աստղանիշով դաշտերը պարտադիր են։"),
"account.register.h1":    ("Register", "Регистрация", "Գրանցում"),
"account.register.standfirst": ("An account is for seeing reports and invoices. Registering costs nothing and orders nothing.",
                                "Аккаунт нужен, чтобы видеть отчёты и счета. Регистрация ничего не стоит и ничего не заказывает.",
                                "Հաշիվը պետք է հաշվետվություններն ու հաշիվները տեսնելու համար։ Գրանցումը ոչինչ չարժե և ոչինչ չի պատվիրում։"),
"account.register.consent":    ("I have read the privacy policy.", "Я ознакомился с политикой конфиденциальности.", "Ես ծանոթացել եմ գաղտնիության քաղաքականությանը։"),
"account.register.submit":     ("Create the account", "Создать аккаунт", "Ստեղծել հաշիվը"),
"account.register.haveaccount":("Already have an account? Sign in.", "Уже есть аккаунт? Войдите.", "Արդեն ունե՞ք հաշիվ։ Մուտք գործեք։"),
"account.reset.h1":       ("Password recovery", "Восстановление пароля", "Գաղտնաբառի վերականգնում"),
"account.reset.standfirst":("Give the address the account is on. If we have it, a link goes to it.",
                            "Укажите адрес, на который заведён аккаунт. Если он у нас есть, на него уйдёт ссылка.",
                            "Նշեք այն հասցեն, որով բացված է հաշիվը։ Եթե այն մեզ մոտ կա, հղումը կուղարկվի դրան։"),
"account.reset.submit":   ("Send the link", "Отправить ссылку", "Ուղարկել հղումը"),
"account.reset.note":     ("The answer is the same whether or not that address is known here. Otherwise this form could be used to find out who has an account.",
                           "Ответ одинаков независимо от того, есть ли такой адрес у нас. Иначе через эту форму можно было бы узнать, у кого есть аккаунт.",
                           "Պատասխանը նույնն է՝ անկախ նրանից՝ այդ հասցեն մեզ մոտ կա, թե ոչ։ Այլապես այս ձևով կարելի կլիներ իմանալ, թե ով ունի հաշիվ։"),
"account.error.summary.title": ("Something is not filled in yet", "Что-то ещё не заполнено", "Ինչ-որ բան դեռ լրացված չէ"),

# ---- footer / misc ---------------------------------------------------------
"account.footer.nav.label": ("Footer", "Нижнее меню", "Ստորին ընտրացանկ"),
}
